import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

import './trip_provider.dart';
import './user_provider.dart';
import './lodging_provider.dart';
import './activity_provider.dart';
import './transportation_provider.dart';
import 'country_provider.dart';

class TripsProvider extends ChangeNotifier {
  List<TripProvider> _trips = [];

  TripsProvider();

  //getter function to return list of trips
  List<TripProvider> get trips {
    return [..._trips];
  }

  TripProvider findById(String id) {
    return _trips.firstWhere((trip) => trip.id == id);
  }

  //Adds a user created trip to their trips list in Firebase Firestore DB
  Future<void> addTrip(TripProvider tripValues, String userId) async {
    print('$userId');
    try {
      await FirebaseFirestore.instance
          .collection('users')
          .doc('$userId')
          .collection('trips')
          .add({
        'title': tripValues.title,
        'startDate': tripValues.startDate,
        'endDate': tripValues.endDate,
        'countries': tripValues.countries
            .map((countries) => {
                  'country': countries.country,
                  'cities': countries.cities
                      .map((cities) => {
                            'city': cities.city,
                            'latitude': cities.latitude,
                            'longitude': cities.longitude,
                          })
                      .toList(),
                  'latitude': countries.latitude,
                  'longitude': countries.longitude,
                })
            .toList(),
        'description': tripValues.description,
        'group': tripValues.group
            .map((group) => {
                  'firstName': group.firstName,
                  'lastName': group.lastName,
                  'email': group.email,
                  'phone': group.phone,
                })
            .toList(),
      }).then((value) {
        print('Trip added');
      }).catchError((onError) {
        print('Failed to add Trip');
        throw onError;
      });

      //Create a TripProvider object with newly aquired autogenerated id.
      //This will be used to add to list of trips in the state
      final newTrip = TripProvider(
        id: null, //ADD CODE TO GET ID
        title: tripValues.title,
        startDate: tripValues.startDate,
        endDate: tripValues.endDate,
        countries: tripValues.countries,
        description: tripValues.description,
        group: tripValues.group,
      );
      _trips.add(newTrip);

      notifyListeners();
    } catch (error) {
      throw error;
    }
  }

  //used to set trips once trips are loaded from firebase
  Future<void> setTripsList(List<TripProvider> loadedTrip) async {
    _trips = loadedTrip;
  }

  //Get trips list of specific user from Firebase Firestore
  Future<void> fetchAndSetTrips(User user) async {
    final List<TripProvider> loadedTrips = [];
    _trips = [];
    try {
      FirebaseFirestore.instance
          .collection('/users/${user.uid}/trips')
          .snapshots()
          .forEach((trip) {
        trip.docs.asMap().forEach((index, data) {
          loadedTrips.add(TripProvider(
            id: trip.docs[index].id,
            title: trip.docs[index].data()['title'],
            startDate: trip.docs[index].data()['startDate'].toDate(),
            endDate: trip.docs[index].data()['endDate'].toDate(),
            description: trip.docs[index].data()['description'],
            group: List.from(trip.docs[index].data()['group']),
            countries: List.from(trip.docs[index].data()['destinations']),
            activities: List.from(trip.docs[index].data()['activities']),
            lodgings: List.from(trip.docs[index].data()['lodgings']),
            transportations:
                List.from(trip.docs[index].data()['transportations']),
            image: trip.docs[index].data()['imageUrl'],
          ));
        });
      });
      await setTripsList(loadedTrips);
      notifyListeners();
    } catch (error) {
      throw error;
    }
  }

  //Update user specified trip in Firebase Firestore
  Future<void> updateTrip(
      String id, TripProvider newTrip, String userId) async {
    final tripIndex = _trips.indexWhere((trip) => trip.id == id);
    if (tripIndex >= 0) {
      try {} catch (error) {
        throw error;
      }
    }
  }
}
